default: cpsc2150/listDec/IShuffleList.java cpsc2150/listDec/ShuffleApp.java cpsc2150/listDec/ShuffleList.java
	javac cpsc2150/listDec/IShuffleList.java cpsc2150/listDec/ShuffleApp.java cpsc2150/listDec/ShuffleList.java

# target to run cpsc2150.listDec.ShuffleApp
run: cpsc2150/listDec/ShuffleApp.class cpsc2150/listDec/ShuffleList.class cpsc2150/listDec/IShuffleList.class
	java cpsc2150.listDec.ShuffleApp

# target to clean the directory by removing all .class files
clean:
	rm -f cpsc2150/listDec/*.class
